- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

      #### just nothing 2 do ####


    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug :
        var: vpcout


    - name: Create pub  subnet 1  for zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{zone1}}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out


