- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

      #### another random code update ####


    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

  #  - debug :
   #     var: vpcout


    - name: Create pub  subnet 1  for zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{zone1}}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out


    - name: Create pub  subnet 2  for zone 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PubSub2Cidr }}"
        az: "{{zone2}}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out


    - name: Create pub  subnet 3  for zone 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PubSub3Cidr }}"
        az: "{{zone3}}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out


    - name: Create pvt  subnet 1  for zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PrivSub1Cidr }}"
        az: "{{zone1}}"
        map_public : yes
        resource_tags:
          Name: vprofile-PrivSub1Cidr1
      register: PrivSub1Cidr_out

    - name: Create pvt  subnet 2  for zone 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PrivSub2Cidr }}"
        az: "{{zone2}}"
        map_public : yes
        resource_tags:
          Name: vprofile-PrivSub1Cidr2
      register: PrivSub2Cidr_out

    - name: Create pvt  subnet 3  for zone 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{ PrivSub3Cidr }}"
        az: "{{zone3}}"
        map_public : yes
        resource_tags:
          Name: vprofile-PrivSub3Cidr3
      register: PrivSub3Cidr_out


    - name: Internet Gateway setup
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: vprofile-IGW
      register: igw_out

    - name : setup RT for pub subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{ region }}"
        tags:
          Name: VProfile-PubRT
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
        register: pubRT_out




