- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

      #### just nothing ####


    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout



    - name: Create pub  subnet 1  for zone 1
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-029cfa2f86e796fd4
        cidr: "{{PubSub1Cidr}}"
        availability_zone: "{{zone1}}"
        tags:
          Name: EC2 Subnet
      register: ec2_subnet


    - name: Create pvt  subnet 1  for zone 1
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-029cfa2f86e796fd4
        cidr: "{{PrivSub1Cidr}}"
        availability_zone: "{{zone1}}"
        tags:
          Name: EC2 Subnet
      register: ec2_subnet

    - name: Create pub  subnet 2  for zone 2
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-029cfa2f86e796fd4
        cidr: "{{PubSub2Cidr}}"
        availability_zone: "{{zone2}}"
        tags:
          Name: EC2 Subnet
      register: ec2_subnet


    - name: Create pvt  subnet 2  for zone 2
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-029cfa2f86e796fd4
        cidr: "{{PrivSub2Cidr}}"
        availability_zone: "{{zone2}}"
        tags:
          Name: EC2 Subnet
      register: ec2_subnet

    - name: Create pub  subnet 3  for zone 3
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-029cfa2f86e796fd4
        cidr: "{{PubSub3Cidr}}"
        availability_zone: "{{zone3}}"
        tags:
          Name: EC2 Subnet
      register: ec2_subnet


    - name: Create pvt  subnet 3  for zone 3
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-029cfa2f86e796fd4
        cidr: "{{PrivSub3Cidr}}"
        availability_zone: "{{zone3}}"
        tags:
          Name: EC2 Subnet
      register: ec2_subnet

