---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc-output_vars

    - name: Import vprofile ec2 setup variable
      include_vars: vars/vprostacksetup

    - name: Import VPC setup variable
      include_vars: vars/vpc_setup


    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: debug vprokey details
      debug:
        var: vprokey_out


    - name: save private key into file loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

#### random changes to update code ###

