---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: yes
  tasks:
    - name: Install Erlang Repository Package
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
      tags:
        - package

    - name: Add an Erlang Solution public Key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      tags:
        - package

    - name: Install Erlang
      apt:
        name: erlang
        update_cache: yes
        cache_valid_time: 86400
        state: present
      tags:
        - package

    - name: Add the RabbitMQ Apt signing key
      apt_key:
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
        state: present
      tags:
        - package

    - name: Add RabbitMQ repository
      apt_repository:
        repo: "deb https://packages.rabbitmq.com/debian {{ ansible_distribution_release }} main"
        state: present
      tags:
        - package

    - name: Verify RabbitMQ repository added correctly
      shell: "grep -r '^deb .*rabbitmq.com/debian' /etc/apt/sources.list /etc/apt/sources.list.d/"
      register: rabbitmq_repo_check
      failed_when: rabbitmq_repo_check.rc != 0
      tags:
        - package

    - name: Update apt cache
      apt:
        update_cache: yes
      when: rabbitmq_repo_check.rc == 0
      tags:
        - package

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
      tags:
        - package

    - name: Start & Enable RabbitMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc

    - name: Configure RabbitMQ
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf

    - name: Enable rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted

