---
- name: Build Artifact ROOT.war & SQL file to be copies in files/ directory
  import_playbook: build.yml

- name: Set Hosts to Ip Mappting in /etc/hosts file of all servers
  import_playbook: set_host_ip_map.yml


- name: Setup dbserver
  import_playbook: db.yml



- name: Deploy SQL file on DBserver
  import_playbook: dbdeploy.yml

#- name: setup memcached service
 # import_playbook: build.yml
## random changes ###


- name:  setup rabbitmq service
  import_playbook: rabbitmq.yml


- name: setup tomcat application server
  import_playbook: appserver.yml


- name: setup nginx webserver
  import_playbook: web.yml